// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;


RcppExport SEXP _rcpp_module_boot_basic_clock();
RcppExport SEXP _rcpp_module_boot_basic_indic();
RcppExport SEXP _rcpp_module_boot_basic_stats();

static const R_CallMethodDef CallEntries[] = {
    {"_rcpp_module_boot_basic_clock", (DL_FUNC) &_rcpp_module_boot_basic_clock, 0},
    {"_rcpp_module_boot_basic_indic", (DL_FUNC) &_rcpp_module_boot_basic_indic, 0},
    {"_rcpp_module_boot_basic_stats", (DL_FUNC) &_rcpp_module_boot_basic_stats, 0},
    {NULL, NULL, 0}
};

RcppExport void R_init_mdtrt(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
